name: perks
description: A sample command-line application.
version: 1.0.0

environment:
    sdk: ">=2.18.0-272.0.dev <3.0.0"

dev_dependencies:
    test: ^1.16.0
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git
            ref: main
