name: perks
description: "📦 Perks is a simple-to-use persistent data storage."
version: 1.0.0
repository: https://github.com/zyrouge/dart_perks

environment:
    sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
    test: ^1.16.0
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git
            ref: main
